### ISSUE TITLE
Oppdage rektor/rådgiver rolle

### ISSUE THREAD

**Issue by maccyber** [telemark/tfk-buddy-api#1]
Trenger en metode for å oppdage rektor/rådgiver rolle

**Comment by maccyber** [comment]
Ser ut som dette utgår i varsel.
Får vurderes om det er behov ved en senere anledning.

**Comment by zrrrzzt** [comment]
Har ikke behov for disse rollene i forbindelse med MinElev og varsel. Stemmer for avslutning.

**Comment by vavaen** [comment]
Rektor/rådgiver har uansett tilgang til elevmappene i 360 og vil få info der.

Fra: Geir Gåsodden [mailto:notifications@github.com]
Sendt: 1. februar 2016 21:53
Til: telemark/tfk-buddy-api <tfk-buddy-api@noreply.github.com>
Emne: Re: [tfk-buddy-api] Oppdage rektor/rådgiver rolle (#1)


Har ikke behov for disse rollene i forbindelse med MinElev og varsel. Stemmer for avslutning.
